### PR TITLE
Update tailwind

### PR DESCRIPTION
**Pull request by occupant**

### CODE REVIEW

**Comment by occupant** [comment]
A few resources about the benefits of utility-based (atomic) vs component-based (object-oriented) css.
Redesigning Our Docs – Part 4 – Building a Scalable CSS Architecture - Algolia Blog
https://blog.algolia.com/redesigning-our-docs-part-4-building-a-scalable-css-architecture/

https://css-tricks.com/need-css-utility-library/

[UBC_Photo_Keynote_16_9_Whitney_2017.pdf](https://github.com/UBCCM/UBC-DEF/files/3056602/UBC_Photo_Keynote_16_9_Whitney_2017.pdf)

Discuss away!

**Comment by occupant** [comment]
The biggest pros in my opinion:

- css is endlessly reusable
- specificity is usually 10 (.class)
- css will not need to be refactored at some point in the future - the classes will continue to be valid and useful
- there's less reason to write any more css

**Comment by hazuremon** [comment]
Hey @occupant,

There seems to be quite a bit going on in your PR (i.e. lint rules, gulp changes, UBC logo, tailwind, etc.), wonder if you can provide us some detail on what these proposed changes are and why are they needed?

As you are proposing multiple features change, from a review and debugging standpoint, as well as multiple discussions that may be needed, would it be possible for you to break down your pull request into multiple smaller pull requests so that each feature can be discuss separately?

Thank you!
Michael

**Comment by richardtape** [comment]
This looks and sounds like a huge amount of work. Thanks so much for pulling it together.

I like the idea and theory behind utility-based design. Never had the chance to use it in practice, so I'm not hugely au fait with the potential pros and cons. Thanks for highlighting what you see as the big pros - **what do you think the cons might be**?

One thing that hits me immediately is the possibility that the HTML becomes super terse. Classes everywhere. I suspect this might be possible to solve with SASS/SCSS mixins, however. I imagine that if we choose to go down this route, documentation - more so than ever - will be very, very important.

One thing I'd love to see, unless it's here and I've just missed it, is some docs about how to start - from scratch - and get the demos you've put together working locally. I'm happy to write that if you can maybe throw the steps at me, or show me face-to-face.

Excited to see where this goes.

**Comment by occupant** [comment]
Thanks both,

@hazuremon yes, I was worried about that. It's almost a refactor, so I wasn't sure whether to just create a new branch and discuss, or chop this into many many pieces so they could be looked at in isolation. The reason I went for one big commit was I think this is really a philosophical / design question. Here's what it could look like - do we want to go there?

At any rate, I agree, I think it would be useful to break this apart. Maybe we can discuss today I can get started on that?

@richardtape I forgot the best resource - the tailwind docs. They're really, really good. [https://next.tailwindcss.com](https://next.tailwindcss.com). Tailwind is MIT, so we could fork the docs and run - although it would be more polite if we ask first :) 

Honestly, the biggest cons I see are:
- **Lack of dev's familiarity** Utility-based css flies in the face of traditional best practice. Mindshare is hard to win.
- **Relying on markup to determine presentation** This is a con in that it's not always easy or possible to modify markup in certain applications. That said, those problems exist equally for component-based frameworks. But tailwind give you a way to continue to use your preset values (via @apply) with any custom selector you need to use.
- **A potentially bigger css file** If you don't purge your css, the tailwind css might seem really, really big. (with all the options, it would be bigger than bootstrap uncompressed). This is mitigated by two things - we don't need a full configuration, and the specificity is so low you can eliminate most if not all of your repaints / reflows. And that's the _really_ expensive part. And there are other ways to tackle this.

When it comes to the classes in the markup, I actually see that as a pro. I have no idea what a class like `.card` might be doing, but if I see the classes `.flex .flex-wrap .bg-ubc-blue` I have a pretty good idea what those are going to do. This seems easier for a novice to grasp. We decouple the reliance on markup and css coordinating, and css is now just an asset to be referenced. 

There's a lot more to say, but I think it would be useful to give a working demo - @hazuremon , @richardtape , do you have time in the next few days or week for an hour or so?

**Pull request closed without merging**
