### PR TITLE
Update .browserlistrc

### PR DESCRIPTION
**Pull request by hazuremon**
#34 

Updated .browserlistrc based on reviewed.

### CODE REVIEW

**Review by occupant — COMMENTED** [review]
The settings look good to me. The only comment I have is that the project recommends using package.json as per: https://github.com/browserslist/browserslist#queries. 

It seems the only reasoning may be reducing files in the project https://github.com/browserslist/browserslist#packagejson, and as long as that's the case, I don't really think it's a big deal.

**Comment by hazuremon** [comment]
I am fine either way, both `browserlist` key in `package.json` and `.browserlistrc` are suggested as an option. 

Both options are always listed together in Google search results I came across, as an equivalent way of setting browser list config.

**Comment by occupant** [comment]
Agreed - I honestly don't think it makes a difference either way, but just wanted to flag it in case you knew about any difference.

**Review by occupant — APPROVED** [review]
All looks good to me

**Pull request merged**
