### PR TITLE
Update gulp syntax

### PR DESCRIPTION
**Pull request by occupant**
Convert gulp file to use ES6 module syntax as per gulp docs:
https://gulpjs.com/docs/en/getting-started/creating-tasks

### CODE REVIEW

**Comment by occupant** [comment]
Even if we abandon Gulp eventually, I don't think we need to do that now. It will just prevent other things from moving forward for very little gain.

I have a build with just scripts in package.json, but there are things that will need to work differently. So this is housekeeping so we can move forward with what we have.

**Comment by hazuremon** [comment]
The reason I suggested to move away from Gulp is because of the outdated packages that leads to vulnerability alerts we are receiving in Github and Snyk.

For example, the gulp-cssnano hasn't been update for well over a year and leads to couple security risks listed in Snyk. In addition to Gulp itself has a high risk alert on the "tar" package.

The way we are using gulp may not be hugely important for these risks, but for long term sustainability, wonder if it will be beneficial if we move to webpack so that the package maintenance falls on the npm package instead of the gulp packages?

**Comment by occupant** [comment]
I agree in principle, yes. The fewer dependencies, the less that can go wrong. That said, it isn't critical at this point and can be done later (adjusting from `gulp styles` to `npm run styles` isn't a big deal). I think to move forward, we should be concentrating on what's critical.

edit:
Also, we should have a final required set of tasks to see what other requirements we may have in terms of packages.

**Review by hazuremon — APPROVED** [review]
Based on an offline discussion with @occupant, we have decided to continue with Gulp before we review on whether we switch to other task runners or package bundler.

**Pull request merged**
